<?php
/**
 * Implements hook_menu().
 */
function cats_bookmarking_menu() {
    $menu = array();

    $menu['pinit1'] = array(
        'title' => 'pinboard',
        'page callback' => 'cats_bookmarking_pinit_js',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
      $menu['recommend1'] = array(
        'title' => 'pinboard',
        'page callback' => 'cats_bookmarking_recommend_js',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    $menu['wishit'] = array(
        'title' => '"Wish It" Button',
        'page callback' => 'cats_bookmarking_addpinit',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
       $menu['recommendit'] = array(
        'title' => '"Recommend It" Button',
        'page callback' => 'cats_bookmarking_recomment',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $menu;
}



function cats_bookmarking_pinit_js() {
    global $base_url;
//status=no,resizable=no,scrollbars=yes,personalbar=no,directories=no,location=no,toolbar=no,menubar=no,width=632,height=670,left=0,top=0
    $t0 = t('Cancel');
    $t1 = t('We need to remove the StumbleUpon toolbar before you can pin anything. Click OK to do this or Cancel to stay here.');
    $t2 = t('Unfortunately, this website doesn\'t allow pinning. You can contact the website owner with any questions you may have regarding their stance on pinning.');
    $t3 = t('Sorry, can\'t pin directly from %privateDomain%.');
    $t4 = t('Sorry, but we cannot see any big images or videos on this page to pin.');
    $t5 = t('The pinning bookmarklet is now installed! You can click the \"Pin It\" button from your bookmarks to pin images from around the web.');
    $t6 = t('Sorry, cannot pin this image.');
    $t7 = t('Sorry, can\'t pin from non-HTML pages. If you\'re trying to upload an image, please visit '.url('', array('absolute' => TRUE)).'.');
    $t8 = t('Pinning is not allowed from this page.\n\n%s% provided the following reason:');

    if (false) {
        $url = str_replace(array('http://','https://'),'',url('node/add/pin', array('absolute' => TRUE)));
        print str_replace(array("\n","\r"),'','
(function(k,m,n,l){var a=k[l.k]={w:k,d:m,n:n,a:l,s:{}

,f:function(){return{callback:[],kill:function(b){if(typeof b==="string")b=a.d.getElementById(b);
b&&b.parentNode&&b.parentNode.removeChild(b)}

,get:function(b,c){var d=null;
return d=b[c]||b.getAttribute(c)}

,make:function(b){var c=false,d,e;

for(d in b)if(b[d].hasOwnProperty){c=a.d.createElement(d);

for(e in b[d])if(b[d][e].hasOwnProperty)if(typeof b[d][e]==="string")c[e]=b[d][e];

break}

return c}

,listen:function(b,c,d){if(typeof a.w.addEventListener!==
"undefined")b.addEventListener(c,d,false);

else typeof a.w.attachEvent!=="undefined"&&b.attachEvent("on"+c,d)}

,getSelection:function(){return(""+(a.w.getSelection?a.w.getSelection():a.d.getSelection?a.d.getSelection():a.d.selection.createRange().text)).replace(/(^\s+|\s+$)/g,"")}

,pin:function(b){var c="";

c=b.getElementsByTagName("IMG")[0];

var d="false",e=a.a.pin+"?",f=(new Date).getTime();

if(b.rel==="video")d="true";

e=e+"media="+encodeURIComponent(b.getAttribute("pinImg"));

e=e+"&url="+encodeURIComponent(c.getAttribute("url")||
a.d.URL);

e=e+"&title="+encodeURIComponent(a.d.title);

e=e+"&is_video="+d;

c=a.v.selectedText||c.title||c.alt;

c=c.substr(0,500);

e=e+"&description="+encodeURIComponent(c);

if(a.v.inlineHandler)e=e+"&via="+encodeURIComponent(a.d.URL);

if(a.v.hazIOS){a.w.setTimeout(function(){a.w.location="pinit12://"+e}

,25);

a.w.location="http://"+e}

else a.w.open("http://"+e,"pin"+f,a.a.pop)}

,close:function(b){if(a.s.bg){a.d.b.removeChild(a.s.shim);

a.d.b.removeChild(a.s.bg);

a.d.b.removeChild(a.s.bd)}

k.hazPinningNow=false;
b&&a.w.alert(b);

a.v.hazGoodUrl=false;

a.w.scroll(0,a.v.saveScrollTop)}

,click:function(b){b=b||a.w.event;

var c=null;

if(c=b.target?b.target.nodeType===3?b.target.parentNode:b.target:b.srcElement)if(c===a.s.x)a.f.close();

else if(c.className!==a.a.k+"_hideMe"){if(!c.className)c=c.parentNode;

if(c.parentNode.className===a.a.k+"_pinContainer"||c.parentNode.parentNode.className===a.a.k+"_pinContainer"||c.className===a.a.k+"_pinButton"){a.f.pin(c.parentNode.getElementsByTagName("A")[0]);

a.w.setTimeout(function(){a.f.close()}

,
10)}

}

}

,behavior:function(){a.f.listen(a.s.bd,"click",a.f.click)}

,presentation:function(){var b=a.f.make({STYLE:{type:"text/css"}

}

),c=a.a.cdn[a.w.location.protocol]||a.a.cdn["http:"],d=a.a.rules.join("\n");

d=d.replace(/#_/g,"#"+l.k+"_");

d=d.replace(/\._/g,"."+l.k+"_");

d=d.replace(/_cdn/g,c);

if(b.styleSheet)b.styleSheet.cssText=d;

else b.appendChild(a.d.createTextNode(d));

a.d.h.appendChild(b)}

,addThumb:function(b,c,d){(d=b.getElementsByTagName(d)[0])?b.insertBefore(c,d):b.appendChild(c)}

,thumb:function(b){var c=
a.a.k+"_thumb_"+b.src;

if(b.src){if(!b.media)b.media="image";

var d=a.f.make({SPAN:{className:a.a.k+"_pinContainer"}

}

),e=a.f.make({A:{rel:b.media}

}

),f=new Image;

f.setAttribute("nopin","nopin");

if(b.title)f.title=b.title;

b.page&&f.setAttribute("url",b.page);

f.style.visibility="hidden";

f.onload=function(){var h=this.width,i=this.height;

if(i>h){this.height=a.a.thumbCellSize;

var j=a.a.thumbCellSize*(h/i);

this.style.width=j;

this.style.marginLeft=a.a.thumbCellSize/2-j/2+"px"}

if(i<h){this.width=a.a.thumbCellSize;


j=a.a.thumbCellSize*(i/h);

this.style.height=j;

this.style.marginTop=a.a.thumbCellSize/2-j/2+"px"}

if(i===h){this.style.height=a.a.thumbCellSize+"px";

this.style.width=a.a.thumbCellSize+"px"}

this.style.visibility=""}

;

f.src=b.thumb?b.thumb:b.src;

e.setAttribute("pinImg",b.src);

e.appendChild(f);

if(b.media!=="image"){f=a.f.make({B:{}

}

);

e.appendChild(f)}

f=a.f.make({CITE:{innerHTML:b.height+" x "+b.width}

}

);

e.appendChild(f);

d.appendChild(e);

d.appendChild(a.f.make({SPAN:{className:a.a.k+"_pinButton"}

}

));

e=false;


if(b.dupe){f=0;

for(var g=a.v.thumbed.length;

f<g;

f+=1)if(a.v.thumbed[f].id.indexOf(b.dupe)!==-1){e=a.v.thumbed[f].id;

break}

}

if(e!==false)if(e=a.d.getElementById(e)){e.parentNode.insertBefore(d,e);

e.parentNode.removeChild(e)}

else b.page||b.media!=="image"?a.f.addThumb(a.s.embedContainer,d,"SPAN"):a.f.addThumb(a.s.imgContainer,d,"SPAN");

else{a.s.imgContainer.appendChild(d);

a.v.hazAtLeastOneGoodThumb+=1}

(b=a.d.getElementById(c))&&b.parentNode.removeChild(b);

d.id=c;

a.v.thumbed.push(d)}

}

,call:function(b,
c){var d=a.f.callback.length,e=a.a.k+".f.callback["+d+"]",f=a.d.createElement("SCRIPT");

a.f.callback[d]=function(g){c(g,d);

a.v.awaitingCallbacks-=1;

a.f.kill(e)}

;

f.id=e;

f.src=b+"&callback="+e;

f.type="text/javascript";

f.charset="utf-8";

a.v.firstScript.parentNode.insertBefore(f,a.v.firstScript);

a.v.awaitingCallbacks+=1}

,ping:{checkDomain:function(b){if(b&&b.disallowed_domains&&b.disallowed_domains.length)for(var c=0,d=b.disallowed_domains.length;

c<d;

c+=1)b.disallowed_domains[c]===a.w.location.host&&
a.f.close(a.a.msg.noPin)}

,info:function(b){if(b)if(b.err)a.f.unThumb(b.id);

else if(b.reply&&b.reply.img&&b.reply.img.src){var c="";

if(b.reply.page)c=b.reply.page;

b.reply.nopin&&b.reply.nopin===1?a.f.unThumb(b.id):a.f.thumb({src:b.reply.img.src,height:b.reply.img.height,width:b.reply.img.width,media:b.reply.media,title:b.reply.description,page:c,dupe:b.id}

)}

}

}

,unThumb:function(b){if(b=a.d.getElementById(a.a.k+"_thumb_"+b)){var c=b.getElementsByTagName("SPAN")[0];

b.removeChild(c);

c=a.f.make({SPAN:{className:a.a.k+
"_hideMe",innerHTML:a.a.msg.grayOut}

}

);

b.appendChild(c);

a.v.hazAtLeastOneGoodThumb-=1}

}

,getExtendedInfo:function(b){if(!a.v.hazCalledForInfo[b]){a.v.hazCalledForInfo[b]=true;

a.f.call(a.a.embed+b,a.f.ping.info)}

}

,getId:function(b){for(var c,d=b.u.split("?")[0].split("#")[0].split("/");

!c;

)c=d.pop();

if(b.r)c=parseInt(c,b.r);

return encodeURIComponent(c)}

,hazUrl:{flickr:function(){var b=a.d.getElementById("image-src");

if(b&&b.href){var c=new Image;

c.onload=function(){a.f.thumb({src:this.src,height:this.height,
width:this.width}

);

a.f.getExtendedInfo("src=flickr&id="+encodeURIComponent(a.v.canonicalImage))}

;

c.src=a.v.canonicalImage=b.href.split("_m.jpg")[0]+"_z.jpg"}

}

,vimeo:function(){var b=a.f.getId({u:a.d.URL,r:10}

);

a.d.getElementsByTagName("DIV");

a.d.getElementsByTagName("LI");

a.d.getElementsByTagName("A");

var c="vimeo";

if(a.d.URL.match(/^https/))c+="_s";

b>1E3&&a.f.getExtendedInfo("src="+c+"&id="+b)}

,youtube:function(){for(var b=a.d.getElementsByTagName("META"),c=0,d=b.length;

c<d;

c+=1){var e=a.f.get(b[c],
"property");

if(e==="og:url"){a.v.canonicalUrl=a.f.get(b[c],"content");

a.v.canonicalId=a.v.canonicalUrl.split("=")[1].split("&")[0]}

if(e==="og:image")a.v.canonicalImage=a.f.get(b[c],"content")}

if(a.v.canonicalImage&&a.v.canonicalUrl){b=new Image;

b.onload=function(){a.f.thumb({src:this.src,height:this.height,width:this.width,type:"video"}

);

a.f.getExtendedInfo("src=youtube&id="+encodeURIComponent(a.v.canonicalId))}

;

b.src=a.v.canonicalImage}

else{a.v.canonicalImage=null;

a.v.canonicalUrl=null}

}

,pinterest:function(){a.f.close(a.a.msg.installed)}

,
facebook:function(){a.f.close(a.a.msg.privateDomain.replace(/%privateDomain%/,"Facebook"))}

,googleReader:function(){a.f.close(a.a.msg.privateDomain.replace(/%privateDomain%/,"Google Reader"))}

,stumbleUpon:function(){var b=0,c=a.a.stumbleFrame.length,d;

for(b=0;

b<c;

b+=1)if(d=a.d.getElementById(a.a.stumbleFrame[b])){a.f.close();

if(a.w.confirm(a.a.msg.bustFrame))a.w.location=d.src;

break}

}

,googleImages:function(){a.v.inlineHandler="google"}

,tumblr:function(){a.v.inlineHandler="tumblr"}

,netflix:function(){a.v.inlineHandler=
"netflix"}

}

,hazSite:{flickr:{img:function(b){if(b.src){b.src=b.src.split("?")[0];

a.f.getExtendedInfo("src=flickr&id="+encodeURIComponent(b.src))}

}

}

,behance:{img:function(b){if(b.src){b.src=b.src.split("?")[0];

a.f.getExtendedInfo("src=behance&id="+encodeURIComponent(b.src))}

}

}

,netflix:{img:function(b){if(b=b.src.split("?")[0].split("#")[0].split("/").pop()){id=parseInt(b.split(".")[0]);

id>1E3&&a.v.inlineHandler&&a.v.inlineHandler==="netflix"&&a.f.getExtendedInfo("src=netflix&id="+id)}

}

}

,youtube:{img:function(b){b=
b.src.split("?")[0].split("#")[0].split("/");

b.pop();

(id=b.pop())&&a.f.getExtendedInfo("src=youtube&id="+id)}

,iframe:function(b){(b=a.f.getId({u:b.src}

))&&a.f.getExtendedInfo("src=youtube&id="+b)}

,video:function(b){(b=b.getAttribute("data-youtube-id"))&&a.f.getExtendedInfo("src=youtube&id="+b)}

,embed:function(b){var c=b.getAttribute("flashvars"),d="";

if(c){if(d=c.split("video_id=")[1])d=d.split("&")[0];

d=encodeURIComponent(d)}

else d=a.f.getId({u:b.src}

);

d&&a.f.getExtendedInfo("src=youtube&id="+d)}

,
object:function(b){b=b.getAttribute("data");

var c="";

if(b)(c=a.f.getId({u:b}

))&&a.f.getExtendedInfo("src=youtube&id="+c)}

}

,vimeo:{iframe:function(b){b=a.f.getId({u:b.src,r:10}

);

b>1E3&&a.f.getExtendedInfo("src=vimeo&id="+b)}

}

}

,parse:function(b,c){b=b.split(c);

if(b[1])return b[1].split("&")[0];

return""}

,handleInline:{google:function(b){var c,d,e=0,f=0;

if(b.src){f=b.parentNode;

if(f.tagName==="A"&&f.href){c=a.f.parse(f.href,"&imgrefurl=");

d=a.f.parse(f.href,"&imgurl=");

e=parseInt(a.f.parse(f.href,"&w="));


f=parseInt(a.f.parse(f.href,"&h="));

d&&c&&f>a.a.minImgSize&&e>a.a.minImgSize&&a.f.thumb({thumb:b.src,src:d,page:c,height:f,width:e}

)}

}

}

,tumblr:function(b){var c=[];

c=null;

c="";

if(b.src){for(c=b.parentNode;

c.tagName!=="LI"&&c!==a.d.b;

)c=c.parentNode;

if(c.tagName==="LI"&&c.parentNode.id==="posts"){c=c.getElementsByTagName("A");

(c=c[c.length-1])&&c.href&&a.f.thumb({src:b.src,page:c.href,height:b.height,width:b.width}

)}

}

}

}

,hazTag:{img:function(b){if(a.v.inlineHandler&&typeof a.f.handleInline[a.v.inlineHandler]===
"function")a.f.handleInline[a.v.inlineHandler](b);

else b.src.match(/^data/)||b.height>a.a.minImgSize&&b.width>a.a.minImgSize&&a.f.thumb({src:b.src,height:b.height,width:b.width}

)}

,meta:function(b){var c,d;

if(b.name&&b.name.toUpperCase()==="PINTEREST"&&b.content&&b.content.toUpperCase()==="NOPIN")if(d=a.f.get(b,"description")){c="The owner of the site";

b=a.d.URL.split("/");

if(b[2])c=b[2];

a.f.close(a.a.msg.noPinReason.replace(/%s%/,c)+"\n\n"+d)}

else a.f.close(a.a.msg.noPin)}

}

,checkTags:function(){var b,
c,d,e,f,g,h,i,j;

a.v.tag=[];

b=0;

for(c=a.a.check.length;

b<c;

b+=1){f=a.d.getElementsByTagName(a.a.check[b]);

d=0;

for(e=f.length;

d<e;

d+=1){g=f[d];

!g.getAttribute("nopin")&&g.style.display!=="none"&&g.style.visibility!=="hidden"&&a.v.tag.push(g)}

}

b=0;

for(c=a.v.tag.length;

b<c;

b+=1){f=a.v.tag[b];

g=f.tagName.toLowerCase();

if(a.a.tag[g])for(h in a.a.tag[g])if(a.a.tag[g][h].hasOwnProperty){i=a.a.tag[g][h];

if(j=a.f.get(f,i.att)){d=0;

for(e=i.match.length;

d<e;

d+=1)j.match(i.match[d])&&a.f.hazSite[h][g](f)}

}

a.f.hazTag[g]&&
a.f.hazTag[g](f)}

}

,getHeight:function(){return Math.max(Math.max(a.d.b.scrollHeight,a.d.d.scrollHeight),Math.max(a.d.b.offsetHeight,a.d.d.offsetHeight),Math.max(a.d.b.clientHeight,a.d.d.clientHeight))}

,structure:function(){a.s.shim=a.f.make({IFRAME:{height:"100%",width:"100%",allowTransparency:true,id:a.a.k+"_shim"}

}

);

a.s.shim.setAttribute("nopin","nopin");

a.d.b.appendChild(a.s.shim);

a.s.bg=a.f.make({DIV:{id:a.a.k+"_bg"}

}

);

a.d.b.appendChild(a.s.bg);

a.s.bd=a.f.make({DIV:{id:a.a.k+"_bd"}

}

);

a.s.x=a.f.make({A:{id:a.a.k+
"_x",innerHTML:a.a.msg.cancelTitle}

}

);

a.s.bd.appendChild(a.s.x);

a.s.bd.appendChild(a.f.make({SPAN:{id:a.a.k+"_logo"}

}

));

a.s.embedContainer=a.f.make({I:{id:a.a.k+"_embedContainer"}

}

);

a.s.bd.appendChild(a.s.embedContainer);

a.s.imgContainer=a.f.make({I:{id:a.a.k+"_imgContainer"}

}

);

a.s.bd.appendChild(a.s.imgContainer);

a.d.b.appendChild(a.s.bd);

var b=a.f.getHeight();

if(a.s.bd.offsetHeight<b){a.s.bd.style.height=b+"px";

a.s.bg.style.height=b+"px";

a.s.shim.style.height=b+"px"}

a.w.scroll(0,0)}

,checkUrl:function(){var b;


for(b in a.a.url)if(a.a.url[b].hasOwnProperty)if(a.d.URL.match(a.a.url[b])){a.f.hazUrl[b]();

if(a.v.hazGoodUrl===false)return false}

return true}

,checkPage:function(){if(a.f.checkUrl()){a.v.canonicalImage||a.f.checkTags();

if(a.v.hazGoodUrl===false)return false}

else return false;

return true}

,init:function(){a.d.d=a.d.documentElement;

a.d.b=a.d.getElementsByTagName("BODY")[0];

a.d.h=a.d.getElementsByTagName("HEAD")[0];

if(!a.d.b||!a.d.h)a.f.close(a.a.msg.noPinIncompletePage);

else if(k.hazPinningNow!==true){k.hazPinningNow=
true;

var b,c=a.n.userAgent;

a.v={saveScrollTop:a.w.pageYOffset,hazGoodUrl:true,hazAtLeastOneGoodThumb:0,awaitingCallbacks:0,thumbed:[],hazIE:function(){return/msie/i.test(c)&&!/opera/i.test(c)}

(),hazIOS:function(){return c.match(/iP/)!==null}

(),firstScript:a.d.getElementsByTagName("SCRIPT")[0],selectedText:a.f.getSelection(),hazCalledForInfo:{}

}

;

b=a.a.checkDomain.url+"?domains="+encodeURIComponent(a.w.location.host);

a.f.call(b,a.f.ping.checkDomain);

a.f.presentation();

a.f.structure();

if(a.f.checkPage())if(a.v.hazGoodUrl===
true){a.f.behavior();

if(a.f.callback.length>1)a.v.waitForCallbacks=a.w.setInterval(function(){if(a.v.awaitingCallbacks===0)if(a.v.hazAtLeastOneGoodThumb===0||a.v.tag.length===0){a.w.clearInterval(a.v.waitForCallbacks);

a.f.close(a.a.msg.notFound)}

}

,500);

else if(!a.v.canonicalImage&&(a.v.hazAtLeastOneGoodThumb===0||a.v.tag.length===0))a.f.close(a.a.msg.notFound)}

}

}

}

}

()}

;

a.f.init()}

)(window,document,navigator,{k:"PIN_"+(new Date).getTime(),checkDomain:{url:"//api.pinterest.com/v2/domains/filter_nopin/"}

,
cdn:{
"https:":"https://a248.e.akamai.net/passets.pinterest.com.s3.amazonaws.com",
"http:":"http://passets-cdn.pinterest.com"}

,embed:"//pinterest.com/embed/?",
pin:"'.$url.'",
minImgSize:80,thumbCellSize:200,check:["meta","iframe","embed","object","img","video","a"],url:{facebook:/^https?:\/\/.*?\.facebook\.com\//,flickr:/^https?:\/\/www\.flickr\.com\//,googleImages:/^https?:\/\/.*?\.google\.com\/search/,googleReader:/^https?:\/\/.*?\.google\.com\/reader\//,netflix:/^https?:\/\/.*?\.netflix\.com/,
pinterest:/^https?:\/\/.*?\.?pinterest\.com\//,stumbleUpon:/^https?:\/\/.*?\.stumbleupon\.com\//,tumblr:/^https?:\/\/www\.tumblr\.com/,vimeo:/^https?:\/\/vimeo\.com\//,youtube:/^https?:\/\/www\.youtube\.com\/watch\?/}

,stumbleFrame:["tb-stumble-frame","stumbleFrame"],tag:{img:{flickr:{att:"src",match:[/staticflickr.com/,/static.flickr.com/]}

,behance:{att:"src",match:[/^http:\/\/behance\.vo\.llnwd\.net/]}

,netflix:{att:"src",match:[/^http:\/\/cdn-?[0-9]\.nflximg\.com/,/^http?s:\/\/netflix\.hs\.llnwd\.net/]}

,
youtube:{att:"src",match:[/ytimg.com\/vi/,/img.youtube.com\/vi/]}

}

,video:{youtube:{att:"src",match:[/videoplayback/]}

}

,embed:{youtube:{att:"src",match:[/^http:\/\/s\.ytimg\.com\/yt/,/^http:\/\/.*?\.?youtube-nocookie\.com\/v/]}

}

,iframe:{youtube:{att:"src",match:[/^http:\/\/www\.youtube\.com\/embed\/([a-zA-Z0-9\-_]+)/]}

,vimeo:{att:"src",match:[/^http?s:\/\/vimeo.com\/(\d+)/,/^http:\/\/player\.vimeo\.com\/video\/(\d+)/]}

}

,object:{youtube:{att:"data",match:[/^http:\/\/.*?\.?youtube-nocookie\.com\/v/]}

}

}

,
msg:{
check:"",
cancelTitle:"'.$t0.'",
grayOut:"'.$t6.'",
noPinIncompletePage:"'.$t7.'",
bustFrame:"'.$t1.'",
noPin:"'.$t2.'",
noPinReason:"'.$t8.'",
privateDomain:"'.$t3.'",
notFound:"'.$t4.'",
installed:"'.$t5.'"
}

,pop:"status=yes,resizable=yes,scrollbars=yes,personalbar=no,directories=yes,location=yes,toolbar=yes,menubar=yes,left=0,top=0",
rules:["#_shim {z-index:8675309;

 position: absolute;

 background: transparent;

 top:0;

 right:0;

 bottom:0;

 left:0;

 width: 100%;

 }

","#_bg {z-index:8675310;

 position: absolute;

 top:0;

 right:0;

 bottom:0;

 left:0;

 background-color:#f2f2f2;

 opacity:.95;

 width: 100%;

 }

","#_bd {z-index:8675311;

 position: absolute;

 text-align: left;

 padding-top: 38px;

 width: 100%;

 top: 0;

 left: 0;

 right: 0;

 font:16px hevetica neue,arial,san-serif;

 }

","#_bd i { font-style:normal;

 }

","#_bd a#_x { z-index:8675332;

 position: fixed;

 *position:absolute;

 width:100%;

 top: 0;

 left: 0;

 right: 0;

 cursor: pointer;

 height: 37px;

 line-height: 36px;

 font-size: 14px;

 font-weight: bold;

 display: block;

 margin: 0;

 background: url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/fullGradient07Normal.png) repeat-x scroll 0 0 #FFFFFF;

 border-bottom: 1px solid #aaa;

 color: #211922;

 text-align: center;

}

",
"#_bd a#_x:active {background-color: #211922;

 background-image: url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/fullGradient07Inverted.png);

 border-color: #211922;

 text-shadow: 0 -1px #211922;

 }

","#_bd a#_x:hover {color: #fff;

 text-decoration: none;

 background-color: #900;

 border-color: #900;

 text-shadow: 0 -1px #900;

}

","#_bd span { z-index:8675312;

 height:200px;

 width:200px;

 overflow:hidden;

 zoom:1;

 display:inline-block;

 background: #fff;

 text-shadow: 0 1px #fff;

 position: relative;

 vertical-align:middle;

 border: 1px solid #aaa;

 border-top: none;

 border-left: none;

}

",
"#_bd span#_logo {background: #FCF9F9 url('.theme_get_setting('logo').') 50% 50% no-repeat;

}

","#_bd span a {z-index:8675314;

 cursor: pointer;

 height: 200px;

 width: 200px;

 }

","#_bd span a img { z-index: 8675316;

 position: absolute;

 top: 0;

 left: 0;

 border: 0;

 margin: 0;

 }

","#_bd span a b {z-index: 8675317;

  position: absolute;

 top: 50%;

 left: 50%;

 height: 50px;

 width: 50px;

 background: transparent url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/VideoIndicator.png) 0 0 no-repeat;

 margin-top: -25px;

 margin-left: -25px;

 }

","#_bd span a cite {z-index: 8675317;

  position: absolute;

 font-size: 10px;

 font-style: normal;

 bottom: 5px;

 width: 100px;

 left: 50%;

 margin-left: -50px;

 text-align: center;

 color: #000;

 background: #fff;

 padding: 3px;

}

",
"#_bd span._pinContainer span._pinButton {z-index: 8675318;

  line-height: 200px;

 font-size: 200px;

 cursor: pointer;

 position: absolute;

 top: 0;

 left: 0;

 height:200px;

 width:200px;

 background: transparent;

 }

","#_bd span._pinContainer span._pinButton:hover {background: transparent url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/W.png) 50% 50% no-repeat;

 }

","#_bd span._pinContainer span._hideMe { z-index: 8675332;

position: absolute;

 height: 200px;

 width: 200px;

 background: rgba(128, 128, 128, .5);

 *background: #aaa;

 line-height: 200px;

 font-size: 10px;

 color: #fff;

 text-align: center;

 font-weight: normal!important;

 }

"]}

);

');
    } else {
        $url = str_replace(array('http:','https:'),'',url('node/add/pin', array('absolute' => TRUE)));
        print str_replace(array("\n","\r"),'','
(function(k,o,p,l){
	var a=k[l.k]={w:k,d:o,n:p,a:l,s:{
  }, f:function(){
		return{
			callback:[],kill:function(b){
				b.parentNode&&b.parentNode.removeChild(b)
			}, get:function(b,c){
				var e=null;
				return e=b[c]||b.getAttribute(c)
			}, make:function(b){
				var c=false,e,d;
				for(e in b)if(b[e].hasOwnProperty){
					c=a.d.createElement(e);
					for(d in b[e]) if(b[e][d].hasOwnProperty) if(typeof b[e][d]==="string") c[d]=b[e][d];
					break
				}

				return c
			} ,listen:function(b,c,e){
				if(typeof a.w.addEventListener!=="undefined")b.addEventListener(c,e,false);
				else typeof a.w.attachEvent!=="undefined"&&b.attachEvent("on"+c,e)
			}, getSelection:function(){
				return(""+(a.w.getSelection?a.w.getSelection():a.d.getSelection?a.d.getSelection():a.d.selection.createRange().text)).replace(/(^\s+|\s+$)/g,"")
			}, pin:function(b){
				var c=b.getElementsByTagName("IMG")[0],e="false",d=a.a.pin+"?",f=(new Date).getTime();
				if(b.rel==="video")e="true";
				d=d+"media="+encodeURIComponent(c.src);
				d=d+"&url="+encodeURIComponent(c.getAttribute("url")||a.d.URL);
				d=d+"&title="+encodeURIComponent(a.d.title);
				d=d+"&is_video="+e;
				d=d+"&description="+encodeURIComponent(a.v.selectedText||c.title||c.alt);
				a.v.hazIOS&&a.w.setTimeout(function(){
					a.w.location="pinit12:"+d
				}, 25);
				a.w.open(d,"pin"+f,a.a.pop)
			}, close:function(b){
				if(a.s.bg){
					a.d.b.removeChild(a.s.shim);
					a.d.b.removeChild(a.s.bg);
					a.d.b.removeChild(a.s.bd)
				}

				k.hazPinningNow=false;
				b&&a.w.alert(b);
				a.v.hazGoodUrl=false;
				a.w.scroll(0,a.v.saveScrollTop)
			}, click:function(b){
				b=b||a.w.event;
				var c=null;
				if(c=b.target?b.target.nodeType===3?b.target.parentNode:b.target:b.srcElement)
					if(c===a.s.x)
					  a.f.close();
					else
						if(c.parentNode.className===a.a.k+"_pinContainer"||c.className===a.a.k+"_pinButton"){
							a.f.pin(c.parentNode.getElementsByTagName("A")[0]);
							a.w.setTimeout(function(){
								a.f.close()
							},10)
						}
			}, behavior:function(){
				a.f.listen(a.s.bd,"click",a.f.click)
			}, presentation:function(){
				var b=a.f.make({
					STYLE:{
						type:"text/css"
					}
				}),c=a.a.rules.join("\n").replace(/#_/g,"#"+l.k+"_").replace(/\._/g,"."+l.k+"_");
				if(b.styleSheet)b.styleSheet.cssText=c;
				else b.appendChild(a.d.createTextNode(c));
				a.d.h.appendChild(b)
			}, thumb:function(b,c,e,d,f,g){
				if(a.v.hazSrc[b]!==true)a.v.hazSrc[b]=true;
				else if(!a.v.hazIE)return;
				a.v.hazAtLeastOneGoodThumb=true;
				d||(d="image");
				var h=a.f.make({
					SPAN:{
						className:a.a.k+"_pinContainer"
					}
				}), j=a.f.make({
					A:{
						rel:d
					}
				}), i=new Image,m,n;
				i.setAttribute("nopin","nopin");
				i.style.visibility="hidden";
				if(f)i.title=f;
				g&&i.setAttribute("url",g);
				i.onload=function(){
					m=this.width;
					n=this.height;
					this.style.marginTop=n<a.a.thumbCellSize?-n/2+"px":"-"+a.a.thumbCellSize/2+"px";
					this.style.marginLeft=m<a.a.thumbCellSize?-m/2+"px":"-"+a.a.thumbCellSize/2+"px";
					this.style.visibility=""
				};
				i.src=b;
				j.appendChild(i);
				if(d!=="image"){
					b=a.f.make({
						B:{
						}
					});
					j.appendChild(b)
				}

				c=a.f.make({
					CITE:{
						innerHTML:c+" x "+e
					}

				});
				j.appendChild(c);
				h.appendChild(j);
				h.appendChild(a.f.make({
					SPAN:{
						className:a.a.k+"_pinButton"
					}

				}));
				if(d!=="image")(d=a.s.bd.getElementsByTagName("SPAN")[1])?d.parentNode.insertBefore(h,d):a.s.bd.appendChild(h);
				else a.s.bd.appendChild(h)
			}, call:function(b,c){
				var e=a.a.k+".f.callback["+a.f.callback.length+"]",d=a.d.createElement("SCRIPT");
				a.f.callback.push(function(f){
					c(f);
					a.f.kill(e)
				});
				d.id=e;
				d.src=b+e;
				d.type="text/javascript";
				d.charset="utf-8";
				a.v.firstScript.parentNode.insertBefore(d,a.v.firstScript)
			}, ping:{
				check:function(b){
					b&&b.ok===false&&a.f.close(a.a.msg.noPin)
				}, vimeo:function(b){
					var c;
					if(b[0]&&b[0].thumbnail_large&&b[0].embed_privacy==="anywhere"){
						c="";
						if(b[0].title)c+=b[0].title;
						if(b[0].user_name)c=c+". Video by "+b[0].user_name;
						if(b[0].user_description)c=c+". "+b[0].user_description;
						c+=".";
						a.f.thumb(b[0].thumbnail_large,150,200,"video",c,b[0].url)
					}
				}
			}, hazUrl:{
				vimeo:function(){
				var b=a.d.URL.split("/").pop(),c=a.d.getElementsByTagName("LI"),e=a.d.getElementsByTagName("A"),d,f;
				b=parseInt(b,10);
				if(b>1&&a.v.hazCalledForThumb["_"+b]!==true){
					a.f.call("http://vimeo.com/api/v2/video/"+b+".json?callback=",a.f.ping.vimeo);
					a.v.hazCalledForThumb["_"+b]=true
				}

				d=c.length;
				for(f=0; f<d; f+=1) if(c[f].id&&c[f].id.split("clip_")[1]){
					b=c[f].id.split("clip_")[1];
					b=parseInt(b,10);
					if(b>1&&a.v.hazCalledForThumb["_"+b]!==true){
						a.v.hazCalledForThumb["_"+b]=true;
						a.f.call("http://vimeo.com/api/v2/video/"+b+".json?callback=",a.f.ping.vimeo)
					}
				}

				d=e.length;
				for(f=0; f<d; f+=1)if(e&&e[f].href){
					b=parseInt(e[f].href.split("/").pop(),10);
					if(b>1&&a.v.hazCalledForThumb["_"+b]!==true){
						a.f.call("http://vimeo.com/api/v2/video/"+b+".json?callback=",a.f.ping.vimeo);
						a.v.hazCalledForThumb["_"+b]=true
					}
				}
			}, pinterest:function(){
				a.f.close(a.a.msg.installed)
			}, facebook:function(){
				a.f.close(a.a.msg.privateDomain.replace(/%privateDomain%/,"Facebook"))
			}, googleReader:function(){
				a.f.close(a.a.msg.privateDomain.replace(/%privateDomain%/,"Google Reader"))
			}, stumbleUpon:function(){
				var b=0,c=a.a.stumbleFrame.length,e;
				for(b=0; b<c; b+=1)if(e=a.d.getElementById(a.a.stumbleFrame[b])){
					a.f.close();
					if(a.w.confirm(a.a.msg.bustFrame)){
						a.d.location=e.src;
						a.w.open(e.src)
					}

					break
				}
			}
		}, hazSite:{
			youtube:{
				iframe:function(b){
					b=b.src.split("?")[0].split("&")[0].split("/");
					a.f.thumb("http://img.youtube.com/vi/"+b.pop()+"/0.jpg",360,480,"video")
				}, video:function(b){
					b.getAttribute("data-youtube-id")&&a.f.thumb("http://img.youtube.com/vi/"+b.getAttribute("data-youtube-id")+"/0.jpg",360,480,"video")
				}, embed:function(b){
					var c=b.getAttribute("flashvars"),e="";
					(e=c?c.split("video_id=")[1].split("&")[0]:b.src.split("?")[0].split("&")[0].split("/").pop())&&a.f.thumb("http://img.youtube.com/vi/"+e+"/0.jpg",360,480,"video")
				}, object:function(b){
					b=b.getAttribute("data");
					var c="";
					if(b)c=b.split("?")[0].split("&")[0].split("/").pop();
					c&&a.f.thumb("http://img.youtube.com/vi/"+c+"/0.jpg",360,480,"video")
				}
			}, vimeo:{
				iframe:function(b){
					a.f.call("http://vimeo.com/api/v2/video/"+b.src.split("/").pop()+".json?callback=",a.f.ping.vimeo)
				}

			}

		},hazTag:{
			img:function(b){
				var c;
				if(!b.src.match(/^data/)){
					c=new Image;
					c.src=b.src;
					c.height>a.a.minImgSize&&c.width>a.a.minImgSize&&a.f.thumb(c.src,c.height,c.width)
				}
			},meta:function(b){
				b.name&&b.name.toUpperCase()==="PINTEREST"&&b.content&&b.content.toUpperCase()==="NOPIN"&&a.f.close(a.a.msg.noPin)
			}
		},checkTags:function(){
			var b,c,e,d,f,g,h,j,i;
			a.v.tag=[];
			b=0;
			for(c=a.a.check.length; b<c; b+=1){
				f=a.d.getElementsByTagName(a.a.check[b]);
				e=0;
				for(d=f.length; e<d; e+=1){
					g=f[e];
					!g.getAttribute("nopin")&&g.style.display!=="none"&&g.style.visibility!=="hidden"&&a.v.tag.push(g)
				}
			}

			b=0;
			for(c=a.v.tag.length;b<c;b+=1){
				f=a.v.tag[b];
				g=f.tagName.toLowerCase();
				if(a.f.hazTag[g])
					a.f.hazTag[g](f);
				else
					if(a.a.tag[g])for(h in a.a.tag[g])if(a.a.tag[g][h].hasOwnProperty){
				j=a.a.tag[g][h];
				if(i=a.f.get(f,j.att)){
					e=0;
					for(d=j.match.length; e<d;e+=1)i.match(j.match[e])&&a.f.hazSite[h][g](f)
				}
			}
		}
	},structure:function(){
		a.s.shim=a.f.make({
			IFRAME:{
				height:"100%",width:"100%",allowTransparency:true,id:a.a.k+"_shim"
			}
		});
		a.s.shim.setAttribute("nopin","nopin");
		a.d.b.appendChild(a.s.shim);
		a.s.bg=a.f.make({
			DIV:{
				id:a.a.k+"_bg"
			}
		});
		a.d.b.appendChild(a.s.bg);
		a.s.bd=a.f.make({
			DIV:{
				id:a.a.k+"_bd"
			}
		});
		a.s.x=a.f.make({
			A:{
				id:a.a.k+"_x",innerHTML:a.a.msg.cancelTitle
			}
		});
		a.s.bd.appendChild(a.s.x);
		a.s.bd.appendChild(a.f.make({
			SPAN:{
				id:a.a.k+"_logo"
			}
		}));
		a.d.b.appendChild(a.s.bd);
		a.w.scroll(0,0)
	},checkUrl:function(){
		var b;
		for(b in a.a.url)if(a.a.url[b].hasOwnProperty)if(a.d.URL.match(a.a.url[b])){
			a.f.hazUrl[b]();
			if(a.v.hazGoodUrl===false)return false
		}

		return true
	},checkPage:function(){
		if(a.f.checkUrl()){
			a.f.checkTags();
			if(a.v.hazGoodUrl===false)return false
		}
		else return false;
		return true
	},init:function(){
		a.d.b=a.d.getElementsByTagName("BODY")[0];
		a.d.h=a.d.getElementsByTagName("HEAD")[0];
		if(!(!a.d.b||!a.d.h||k.hazPinningNow===true)){
			var b,c=a.n.userAgent;
			a.v={
				saveScrollTop:a.w.pageYOffset,hazGoodUrl:true,hazAtLeastOneGoodThumb:false,hazSrc:{
			},hazCalledForThumb:{
		},hazIE:function(){
			return/msie/i.test(c)&&!/opera/i.test(c)
		}(),hazIOS:function(){
			return c.match(/iP/)!==null
		}(),firstScript:a.d.getElementsByTagName("SCRIPT")[0],selectedText:a.f.getSelection()
	};
	b=a.a.checkpoint.url+"?url="+encodeURIComponent(a.d.URL)+"&callback=";
	a.f.call(b,a.f.ping.check);
	a.f.structure();
	a.f.presentation();
	if(a.f.checkPage())if(a.v.hazGoodUrl===true){
		a.f.behavior();
		if(!(a.f.callback.length>1))if(a.v.hazAtLeastOneGoodThumb===false||a.v.tag.length===0){
			a.f.close(a.a.msg.notFound);
			return
		}
	}

	k.hazPinningNow=true
}
}
}
}()
};
a.f.init()
})(window,document,navigator,{
	k:"PIN_"+(new Date).getTime(),
	checkpoint:{
		url:"'.$url.'"
	},pin:"'.$url.'",minImgSize:80,thumbCellSize:200,check:["meta","iframe","embed","object","img","video"],
		url:{
			vimeo:/^https?:\/\/.*?\.?vimeo\.com\//,facebook:/^https?:\/\/.*?\.?facebook\.com\//,googleReader:/^https?:\/\/.*?\.?google\.com\/reader\//,pinterest:/^https?:\/\/.*?\.?pinterest\.com\//,stumbleUpon:/^https?:\/\/.*?\.?stumbleupon\.com\//
		},
		stumbleFrame:["tb-stumble-frame","stumbleFrame"],
		tag:{
		video:{
			youtube:{
				att:"src",
				match:[/videoplayback/]
			}
		},
		embed:{
			youtube:{
				att:"src",match:[/^http:\/\/s\.ytimg\.com\/yt/,/^http:\/\/.*?\.?youtube-nocookie\.com\/v/]
			}
		},
		iframe:{
			youtube:{
				att:"src",match:[/^http:\/\/www\.youtube\.com\/embed\/([a-zA-Z0-9\-_]+)/]
			},
			vimeo:{
				att:"src",match:[/^http?s:\/\/vimeo.com\/(\d+)/,/^http:\/\/player\.vimeo\.com\/video\/(\d+)/]
			}
		},
		object:{
			youtube:{
				att:"data",match:[/^http:\/\/.*?\.?youtube-nocookie\.com\/v/]
			}
		}
	},
	msg:{
		check:"",
		cancelTitle:"'.$t0.'",
		bustFrame:"'.$t1.'",
		noPin:"'.$t2.'",
		privateDomain:"'.$t3.'",
		notFound:"'.$t4.'",
		installed:"'.$t5.'"
	},
	pop:"status=yes,resizable=yes,scrollbars=yes,personalbar=no,directories=yes,location=yes,toolbar=yes,menubar=yes,left=0,top=0",
		rules:["#_bg {
		position:fixed;
		z-index:8675309;
 		top:0;
 		right:0;
 		bottom:0;
 		left:0;
 		background-color:#e2e2e2;
 		opacity:.95;
	}","
	#_shim {
		position:fixed;
 		background: transparent;
 		z-index:8675308;
 		top:0;
 		right:0;
 		bottom:0;
 		left:0;
	}","
	#_bd {
		position: absolute;
 		text-align: left;
 		padding-top: 36px;
 		top: 0;
 		left: 0;
 		right: 0;
 		z-index:8675320;
 		font:16px hevetica neue,arial,san-serif;
	}","
	#_bd span {
 		zoom:1;
 		display: inline-block;
 		background: #fff;
 		height:200px;
 		width:200px;
 		border: 1px solid #bbb;
 		border-top: none;
 		border-left:none;
 		text-decoration: none;
  	text-shadow: 0 1px #fff;
 		position: relative;
 		cursor: pointer;
 		vertical-align:middle;
	}","
	#_bd span#_logo {
		background: #FCF9F9 url('.theme_get_setting('logo').') 50% 50% no-repeat;
 		box-shadow: none;
	}","
	#_bd a#_x {
		height: 36px;
 		line-height: 36px;
 		position: fixed;
 		font-size: 14px;
 		font-weight: bold;
 		display: block;
 		width:auto;
 		top: 0;
 		left: 0;
 		right: 0;
 		margin: 0;
 		background: url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/fullGradient07Normal.png) repeat-x scroll 0 0 #FFFFFF;
 		border-bottom: 1px solid #bbb;
 		color: #211922;
 		text-align: center;
 		z-index:8675321;
	}","
	#_bd a#_x:active {
		background-color: #211922;
 		background-image: url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/fullGradient07Inverted.png);
 		border-color: #211922;
 		text-shadow: 0 -1px #211922;
	}","
	#_bd a#_x:hover {
		color: #fff;
 		text-decoration: none;
 		background-color: #900;

 		border-color: #900;
 		text-shadow: 1px 1px #600;
	}","
	#_bd a img {
		max-height:200px;
 		max-width:200px;
 		top: 50%;
 		left: 50%;
 		position: absolute;
 		z-index:8675312;
	}","
	#_bd a b {
 		z-index: 8675315;
 		position: absolute;
 		top: 50%;
 		left: 50%;
 		height: 50px;
 		width: 50px;
 		background: transparent url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/VideoIndicator.png) 0 0 no-repeat;
 		margin-top: -25px;
 		margin-left: -25px;
	}","
	#_bd a cite {
		z-index: 8675316;
 		position: absolute;
 		font-size: 10px;
 		font-style: normal;
 		bottom: 5px;
 		width: 100px;
 		left: 50%;
 		margin-left: -50px;
 		text-align: center;
 		color: #000;
 		background: #fff;
 		padding: 3px;
	}","
	#_bd span._pinContainer {
		z-index: 8675320;
 		height: 200px;
 		width: 200px;
 		background: #fff;
	}","
	#_bd span._pinButton {
		z-index: 8675320;
 		height: 200px;
 		width: 200px;
 		background: transparent;
	}","
	#_bd span._pinButton:hover {
		height: 200px;
 		width: 200px;
 		background: transparent url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/W.png) 50% 50% no-repeat;
	}"]

});
');
    }
    exit;
}
function cats_bookmarking_recommend_js() {
    global $base_url;
//status=no,resizable=no,scrollbars=yes,personalbar=no,directories=no,location=no,toolbar=no,menubar=no,width=632,height=670,left=0,top=0
    $t0 = t('Cancel');
    $t1 = t('We need to remove the StumbleUpon toolbar before you can pin anything. Click OK to do this or Cancel to stay here.');
    $t2 = t('Unfortunately, this website doesn\'t allow pinning. You can contact the website owner with any questions you may have regarding their stance on pinning.');
    $t3 = t('Sorry, can\'t pin directly from %privateDomain%.');
    $t4 = t('Sorry, but we cannot see any big images or videos on this page to pin.');
    $t5 = t('The pinning bookmarklet is now installed! You can click the \"Pin It\" button from your bookmarks to pin images from around the web.');
    $t6 = t('Sorry, cannot pin this image.');
    $t7 = t('Sorry, can\'t pin from non-HTML pages. If you\'re trying to upload an image, please visit '.url('', array('absolute' => TRUE)).'.');
    $t8 = t('Pinning is not allowed from this page.\n\n%s% provided the following reason:');

    if (false) {
        $url = str_replace(array('http://','https://'),'',url('bookmarks_clone', array('absolute' => TRUE)));
        print str_replace(array("\n","\r"),'','
(function(k,m,n,l){var a=k[l.k]={w:k,d:m,n:n,a:l,s:{}

,f:function(){return{callback:[],kill:function(b){if(typeof b==="string")b=a.d.getElementById(b);
b&&b.parentNode&&b.parentNode.removeChild(b)}

,get:function(b,c){var d=null;
return d=b[c]||b.getAttribute(c)}

,make:function(b){var c=false,d,e;

for(d in b)if(b[d].hasOwnProperty){c=a.d.createElement(d);

for(e in b[d])if(b[d][e].hasOwnProperty)if(typeof b[d][e]==="string")c[e]=b[d][e];

break}

return c}

,listen:function(b,c,d){if(typeof a.w.addEventListener!==
"undefined")b.addEventListener(c,d,false);

else typeof a.w.attachEvent!=="undefined"&&b.attachEvent("on"+c,d)}

,getSelection:function(){return(""+(a.w.getSelection?a.w.getSelection():a.d.getSelection?a.d.getSelection():a.d.selection.createRange().text)).replace(/(^\s+|\s+$)/g,"")}

,pin:function(b){var c="";

c=b.getElementsByTagName("IMG")[0];

var d="false",e=a.a.pin+"?",f=(new Date).getTime();

if(b.rel==="video")d="true";

e=e+"media="+encodeURIComponent(b.getAttribute("pinImg"));

e=e+"&url="+encodeURIComponent(c.getAttribute("url")||
a.d.URL);

e=e+"&title="+encodeURIComponent(a.d.title);

e=e+"&is_video="+d;

c=a.v.selectedText||c.title||c.alt;

c=c.substr(0,500);

e=e+"&description="+encodeURIComponent(c);

if(a.v.inlineHandler)e=e+"&via="+encodeURIComponent(a.d.URL);

if(a.v.hazIOS){a.w.setTimeout(function(){a.w.location="pinit12://"+e}

,25);

a.w.location="http://"+e}

else a.w.open("http://"+e,"pin"+f,a.a.pop)}

,close:function(b){if(a.s.bg){a.d.b.removeChild(a.s.shim);

a.d.b.removeChild(a.s.bg);

a.d.b.removeChild(a.s.bd)}

k.hazPinningNow=false;
b&&a.w.alert(b);

a.v.hazGoodUrl=false;

a.w.scroll(0,a.v.saveScrollTop)}

,click:function(b){b=b||a.w.event;

var c=null;

if(c=b.target?b.target.nodeType===3?b.target.parentNode:b.target:b.srcElement)if(c===a.s.x)a.f.close();

else if(c.className!==a.a.k+"_hideMe"){if(!c.className)c=c.parentNode;

if(c.parentNode.className===a.a.k+"_pinContainer"||c.parentNode.parentNode.className===a.a.k+"_pinContainer"||c.className===a.a.k+"_pinButton"){a.f.pin(c.parentNode.getElementsByTagName("A")[0]);

a.w.setTimeout(function(){a.f.close()}

,
10)}

}

}

,behavior:function(){a.f.listen(a.s.bd,"click",a.f.click)}

,presentation:function(){var b=a.f.make({STYLE:{type:"text/css"}

}

),c=a.a.cdn[a.w.location.protocol]||a.a.cdn["http:"],d=a.a.rules.join("\n");

d=d.replace(/#_/g,"#"+l.k+"_");

d=d.replace(/\._/g,"."+l.k+"_");

d=d.replace(/_cdn/g,c);

if(b.styleSheet)b.styleSheet.cssText=d;

else b.appendChild(a.d.createTextNode(d));

a.d.h.appendChild(b)}

,addThumb:function(b,c,d){(d=b.getElementsByTagName(d)[0])?b.insertBefore(c,d):b.appendChild(c)}

,thumb:function(b){var c=
a.a.k+"_thumb_"+b.src;

if(b.src){if(!b.media)b.media="image";

var d=a.f.make({SPAN:{className:a.a.k+"_pinContainer"}

}

),e=a.f.make({A:{rel:b.media}

}

),f=new Image;

f.setAttribute("nopin","nopin");

if(b.title)f.title=b.title;

b.page&&f.setAttribute("url",b.page);

f.style.visibility="hidden";

f.onload=function(){var h=this.width,i=this.height;

if(i>h){this.height=a.a.thumbCellSize;

var j=a.a.thumbCellSize*(h/i);

this.style.width=j;

this.style.marginLeft=a.a.thumbCellSize/2-j/2+"px"}

if(i<h){this.width=a.a.thumbCellSize;


j=a.a.thumbCellSize*(i/h);

this.style.height=j;

this.style.marginTop=a.a.thumbCellSize/2-j/2+"px"}

if(i===h){this.style.height=a.a.thumbCellSize+"px";

this.style.width=a.a.thumbCellSize+"px"}

this.style.visibility=""}

;

f.src=b.thumb?b.thumb:b.src;

e.setAttribute("pinImg",b.src);

e.appendChild(f);

if(b.media!=="image"){f=a.f.make({B:{}

}

);

e.appendChild(f)}

f=a.f.make({CITE:{innerHTML:b.height+" x "+b.width}

}

);

e.appendChild(f);

d.appendChild(e);

d.appendChild(a.f.make({SPAN:{className:a.a.k+"_pinButton"}

}

));

e=false;


if(b.dupe){f=0;

for(var g=a.v.thumbed.length;

f<g;

f+=1)if(a.v.thumbed[f].id.indexOf(b.dupe)!==-1){e=a.v.thumbed[f].id;

break}

}

if(e!==false)if(e=a.d.getElementById(e)){e.parentNode.insertBefore(d,e);

e.parentNode.removeChild(e)}

else b.page||b.media!=="image"?a.f.addThumb(a.s.embedContainer,d,"SPAN"):a.f.addThumb(a.s.imgContainer,d,"SPAN");

else{a.s.imgContainer.appendChild(d);

a.v.hazAtLeastOneGoodThumb+=1}

(b=a.d.getElementById(c))&&b.parentNode.removeChild(b);

d.id=c;

a.v.thumbed.push(d)}

}

,call:function(b,
c){var d=a.f.callback.length,e=a.a.k+".f.callback["+d+"]",f=a.d.createElement("SCRIPT");

a.f.callback[d]=function(g){c(g,d);

a.v.awaitingCallbacks-=1;

a.f.kill(e)}

;

f.id=e;

f.src=b+"&callback="+e;

f.type="text/javascript";

f.charset="utf-8";

a.v.firstScript.parentNode.insertBefore(f,a.v.firstScript);

a.v.awaitingCallbacks+=1}

,ping:{checkDomain:function(b){if(b&&b.disallowed_domains&&b.disallowed_domains.length)for(var c=0,d=b.disallowed_domains.length;

c<d;

c+=1)b.disallowed_domains[c]===a.w.location.host&&
a.f.close(a.a.msg.noPin)}

,info:function(b){if(b)if(b.err)a.f.unThumb(b.id);

else if(b.reply&&b.reply.img&&b.reply.img.src){var c="";

if(b.reply.page)c=b.reply.page;

b.reply.nopin&&b.reply.nopin===1?a.f.unThumb(b.id):a.f.thumb({src:b.reply.img.src,height:b.reply.img.height,width:b.reply.img.width,media:b.reply.media,title:b.reply.description,page:c,dupe:b.id}

)}

}

}

,unThumb:function(b){if(b=a.d.getElementById(a.a.k+"_thumb_"+b)){var c=b.getElementsByTagName("SPAN")[0];

b.removeChild(c);

c=a.f.make({SPAN:{className:a.a.k+
"_hideMe",innerHTML:a.a.msg.grayOut}

}

);

b.appendChild(c);

a.v.hazAtLeastOneGoodThumb-=1}

}

,getExtendedInfo:function(b){if(!a.v.hazCalledForInfo[b]){a.v.hazCalledForInfo[b]=true;

a.f.call(a.a.embed+b,a.f.ping.info)}

}

,getId:function(b){for(var c,d=b.u.split("?")[0].split("#")[0].split("/");

!c;

)c=d.pop();

if(b.r)c=parseInt(c,b.r);

return encodeURIComponent(c)}

,hazUrl:{flickr:function(){var b=a.d.getElementById("image-src");

if(b&&b.href){var c=new Image;

c.onload=function(){a.f.thumb({src:this.src,height:this.height,
width:this.width}

);

a.f.getExtendedInfo("src=flickr&id="+encodeURIComponent(a.v.canonicalImage))}

;

c.src=a.v.canonicalImage=b.href.split("_m.jpg")[0]+"_z.jpg"}

}

,vimeo:function(){var b=a.f.getId({u:a.d.URL,r:10}

);

a.d.getElementsByTagName("DIV");

a.d.getElementsByTagName("LI");

a.d.getElementsByTagName("A");

var c="vimeo";

if(a.d.URL.match(/^https/))c+="_s";

b>1E3&&a.f.getExtendedInfo("src="+c+"&id="+b)}

,youtube:function(){for(var b=a.d.getElementsByTagName("META"),c=0,d=b.length;

c<d;

c+=1){var e=a.f.get(b[c],
"property");

if(e==="og:url"){a.v.canonicalUrl=a.f.get(b[c],"content");

a.v.canonicalId=a.v.canonicalUrl.split("=")[1].split("&")[0]}

if(e==="og:image")a.v.canonicalImage=a.f.get(b[c],"content")}

if(a.v.canonicalImage&&a.v.canonicalUrl){b=new Image;

b.onload=function(){a.f.thumb({src:this.src,height:this.height,width:this.width,type:"video"}

);

a.f.getExtendedInfo("src=youtube&id="+encodeURIComponent(a.v.canonicalId))}

;

b.src=a.v.canonicalImage}

else{a.v.canonicalImage=null;

a.v.canonicalUrl=null}

}

,pinterest:function(){a.f.close(a.a.msg.installed)}

,
facebook:function(){a.f.close(a.a.msg.privateDomain.replace(/%privateDomain%/,"Facebook"))}

,googleReader:function(){a.f.close(a.a.msg.privateDomain.replace(/%privateDomain%/,"Google Reader"))}

,stumbleUpon:function(){var b=0,c=a.a.stumbleFrame.length,d;

for(b=0;

b<c;

b+=1)if(d=a.d.getElementById(a.a.stumbleFrame[b])){a.f.close();

if(a.w.confirm(a.a.msg.bustFrame))a.w.location=d.src;

break}

}

,googleImages:function(){a.v.inlineHandler="google"}

,tumblr:function(){a.v.inlineHandler="tumblr"}

,netflix:function(){a.v.inlineHandler=
"netflix"}

}

,hazSite:{flickr:{img:function(b){if(b.src){b.src=b.src.split("?")[0];

a.f.getExtendedInfo("src=flickr&id="+encodeURIComponent(b.src))}

}

}

,behance:{img:function(b){if(b.src){b.src=b.src.split("?")[0];

a.f.getExtendedInfo("src=behance&id="+encodeURIComponent(b.src))}

}

}

,netflix:{img:function(b){if(b=b.src.split("?")[0].split("#")[0].split("/").pop()){id=parseInt(b.split(".")[0]);

id>1E3&&a.v.inlineHandler&&a.v.inlineHandler==="netflix"&&a.f.getExtendedInfo("src=netflix&id="+id)}

}

}

,youtube:{img:function(b){b=
b.src.split("?")[0].split("#")[0].split("/");

b.pop();

(id=b.pop())&&a.f.getExtendedInfo("src=youtube&id="+id)}

,iframe:function(b){(b=a.f.getId({u:b.src}

))&&a.f.getExtendedInfo("src=youtube&id="+b)}

,video:function(b){(b=b.getAttribute("data-youtube-id"))&&a.f.getExtendedInfo("src=youtube&id="+b)}

,embed:function(b){var c=b.getAttribute("flashvars"),d="";

if(c){if(d=c.split("video_id=")[1])d=d.split("&")[0];

d=encodeURIComponent(d)}

else d=a.f.getId({u:b.src}

);

d&&a.f.getExtendedInfo("src=youtube&id="+d)}

,
object:function(b){b=b.getAttribute("data");

var c="";

if(b)(c=a.f.getId({u:b}

))&&a.f.getExtendedInfo("src=youtube&id="+c)}

}

,vimeo:{iframe:function(b){b=a.f.getId({u:b.src,r:10}

);

b>1E3&&a.f.getExtendedInfo("src=vimeo&id="+b)}

}

}

,parse:function(b,c){b=b.split(c);

if(b[1])return b[1].split("&")[0];

return""}

,handleInline:{google:function(b){var c,d,e=0,f=0;

if(b.src){f=b.parentNode;

if(f.tagName==="A"&&f.href){c=a.f.parse(f.href,"&imgrefurl=");

d=a.f.parse(f.href,"&imgurl=");

e=parseInt(a.f.parse(f.href,"&w="));


f=parseInt(a.f.parse(f.href,"&h="));

d&&c&&f>a.a.minImgSize&&e>a.a.minImgSize&&a.f.thumb({thumb:b.src,src:d,page:c,height:f,width:e}

)}

}

}

,tumblr:function(b){var c=[];

c=null;

c="";

if(b.src){for(c=b.parentNode;

c.tagName!=="LI"&&c!==a.d.b;

)c=c.parentNode;

if(c.tagName==="LI"&&c.parentNode.id==="posts"){c=c.getElementsByTagName("A");

(c=c[c.length-1])&&c.href&&a.f.thumb({src:b.src,page:c.href,height:b.height,width:b.width}

)}

}

}

}

,hazTag:{img:function(b){if(a.v.inlineHandler&&typeof a.f.handleInline[a.v.inlineHandler]===
"function")a.f.handleInline[a.v.inlineHandler](b);

else b.src.match(/^data/)||b.height>a.a.minImgSize&&b.width>a.a.minImgSize&&a.f.thumb({src:b.src,height:b.height,width:b.width}

)}

,meta:function(b){var c,d;

if(b.name&&b.name.toUpperCase()==="PINTEREST"&&b.content&&b.content.toUpperCase()==="NOPIN")if(d=a.f.get(b,"description")){c="The owner of the site";

b=a.d.URL.split("/");

if(b[2])c=b[2];

a.f.close(a.a.msg.noPinReason.replace(/%s%/,c)+"\n\n"+d)}

else a.f.close(a.a.msg.noPin)}

}

,checkTags:function(){var b,
c,d,e,f,g,h,i,j;

a.v.tag=[];

b=0;

for(c=a.a.check.length;

b<c;

b+=1){f=a.d.getElementsByTagName(a.a.check[b]);

d=0;

for(e=f.length;

d<e;

d+=1){g=f[d];

!g.getAttribute("nopin")&&g.style.display!=="none"&&g.style.visibility!=="hidden"&&a.v.tag.push(g)}

}

b=0;

for(c=a.v.tag.length;

b<c;

b+=1){f=a.v.tag[b];

g=f.tagName.toLowerCase();

if(a.a.tag[g])for(h in a.a.tag[g])if(a.a.tag[g][h].hasOwnProperty){i=a.a.tag[g][h];

if(j=a.f.get(f,i.att)){d=0;

for(e=i.match.length;

d<e;

d+=1)j.match(i.match[d])&&a.f.hazSite[h][g](f)}

}

a.f.hazTag[g]&&
a.f.hazTag[g](f)}

}

,getHeight:function(){return Math.max(Math.max(a.d.b.scrollHeight,a.d.d.scrollHeight),Math.max(a.d.b.offsetHeight,a.d.d.offsetHeight),Math.max(a.d.b.clientHeight,a.d.d.clientHeight))}

,structure:function(){a.s.shim=a.f.make({IFRAME:{height:"100%",width:"100%",allowTransparency:true,id:a.a.k+"_shim"}

}

);

a.s.shim.setAttribute("nopin","nopin");

a.d.b.appendChild(a.s.shim);

a.s.bg=a.f.make({DIV:{id:a.a.k+"_bg"}

}

);

a.d.b.appendChild(a.s.bg);

a.s.bd=a.f.make({DIV:{id:a.a.k+"_bd"}

}

);

a.s.x=a.f.make({A:{id:a.a.k+
"_x",innerHTML:a.a.msg.cancelTitle}

}

);

a.s.bd.appendChild(a.s.x);

a.s.bd.appendChild(a.f.make({SPAN:{id:a.a.k+"_logo"}

}

));

a.s.embedContainer=a.f.make({I:{id:a.a.k+"_embedContainer"}

}

);

a.s.bd.appendChild(a.s.embedContainer);

a.s.imgContainer=a.f.make({I:{id:a.a.k+"_imgContainer"}

}

);

a.s.bd.appendChild(a.s.imgContainer);

a.d.b.appendChild(a.s.bd);

var b=a.f.getHeight();

if(a.s.bd.offsetHeight<b){a.s.bd.style.height=b+"px";

a.s.bg.style.height=b+"px";

a.s.shim.style.height=b+"px"}

a.w.scroll(0,0)}

,checkUrl:function(){var b;


for(b in a.a.url)if(a.a.url[b].hasOwnProperty)if(a.d.URL.match(a.a.url[b])){a.f.hazUrl[b]();

if(a.v.hazGoodUrl===false)return false}

return true}

,checkPage:function(){if(a.f.checkUrl()){a.v.canonicalImage||a.f.checkTags();

if(a.v.hazGoodUrl===false)return false}

else return false;

return true}

,init:function(){a.d.d=a.d.documentElement;

a.d.b=a.d.getElementsByTagName("BODY")[0];

a.d.h=a.d.getElementsByTagName("HEAD")[0];

if(!a.d.b||!a.d.h)a.f.close(a.a.msg.noPinIncompletePage);

else if(k.hazPinningNow!==true){k.hazPinningNow=
true;

var b,c=a.n.userAgent;

a.v={saveScrollTop:a.w.pageYOffset,hazGoodUrl:true,hazAtLeastOneGoodThumb:0,awaitingCallbacks:0,thumbed:[],hazIE:function(){return/msie/i.test(c)&&!/opera/i.test(c)}

(),hazIOS:function(){return c.match(/iP/)!==null}

(),firstScript:a.d.getElementsByTagName("SCRIPT")[0],selectedText:a.f.getSelection(),hazCalledForInfo:{}

}

;

b=a.a.checkDomain.url+"?domains="+encodeURIComponent(a.w.location.host);

a.f.call(b,a.f.ping.checkDomain);

a.f.presentation();

a.f.structure();

if(a.f.checkPage())if(a.v.hazGoodUrl===
true){a.f.behavior();

if(a.f.callback.length>1)a.v.waitForCallbacks=a.w.setInterval(function(){if(a.v.awaitingCallbacks===0)if(a.v.hazAtLeastOneGoodThumb===0||a.v.tag.length===0){a.w.clearInterval(a.v.waitForCallbacks);

a.f.close(a.a.msg.notFound)}

}

,500);

else if(!a.v.canonicalImage&&(a.v.hazAtLeastOneGoodThumb===0||a.v.tag.length===0))a.f.close(a.a.msg.notFound)}

}

}

}

}

()}

;

a.f.init()}

)(window,document,navigator,{k:"PIN_"+(new Date).getTime(),checkDomain:{url:"//api.pinterest.com/v2/domains/filter_nopin/"}

,
cdn:{
"https:":"https://a248.e.akamai.net/passets.pinterest.com.s3.amazonaws.com",
"http:":"http://passets-cdn.pinterest.com"}

,embed:"//pinterest.com/embed/?",
pin:"'.$url.'",
minImgSize:80,thumbCellSize:200,check:["meta","iframe","embed","object","img","video","a"],url:{facebook:/^https?:\/\/.*?\.facebook\.com\//,flickr:/^https?:\/\/www\.flickr\.com\//,googleImages:/^https?:\/\/.*?\.google\.com\/search/,googleReader:/^https?:\/\/.*?\.google\.com\/reader\//,netflix:/^https?:\/\/.*?\.netflix\.com/,
pinterest:/^https?:\/\/.*?\.?pinterest\.com\//,stumbleUpon:/^https?:\/\/.*?\.stumbleupon\.com\//,tumblr:/^https?:\/\/www\.tumblr\.com/,vimeo:/^https?:\/\/vimeo\.com\//,youtube:/^https?:\/\/www\.youtube\.com\/watch\?/}

,stumbleFrame:["tb-stumble-frame","stumbleFrame"],tag:{img:{flickr:{att:"src",match:[/staticflickr.com/,/static.flickr.com/]}

,behance:{att:"src",match:[/^http:\/\/behance\.vo\.llnwd\.net/]}

,netflix:{att:"src",match:[/^http:\/\/cdn-?[0-9]\.nflximg\.com/,/^http?s:\/\/netflix\.hs\.llnwd\.net/]}

,
youtube:{att:"src",match:[/ytimg.com\/vi/,/img.youtube.com\/vi/]}

}

,video:{youtube:{att:"src",match:[/videoplayback/]}

}

,embed:{youtube:{att:"src",match:[/^http:\/\/s\.ytimg\.com\/yt/,/^http:\/\/.*?\.?youtube-nocookie\.com\/v/]}

}

,iframe:{youtube:{att:"src",match:[/^http:\/\/www\.youtube\.com\/embed\/([a-zA-Z0-9\-_]+)/]}

,vimeo:{att:"src",match:[/^http?s:\/\/vimeo.com\/(\d+)/,/^http:\/\/player\.vimeo\.com\/video\/(\d+)/]}

}

,object:{youtube:{att:"data",match:[/^http:\/\/.*?\.?youtube-nocookie\.com\/v/]}

}

}

,
msg:{
check:"",
cancelTitle:"'.$t0.'",
grayOut:"'.$t6.'",
noPinIncompletePage:"'.$t7.'",
bustFrame:"'.$t1.'",
noPin:"'.$t2.'",
noPinReason:"'.$t8.'",
privateDomain:"'.$t3.'",
notFound:"'.$t4.'",
installed:"'.$t5.'"
}

,pop:"status=yes,resizable=yes,scrollbars=yes,personalbar=no,directories=yes,location=yes,toolbar=yes,menubar=yes,left=0,top=0",
rules:["#_shim {z-index:8675309;

 position: absolute;

 background: transparent;

 top:0;

 right:0;

 bottom:0;

 left:0;

 width: 100%;

 }

","#_bg {z-index:8675310;

 position: absolute;

 top:0;

 right:0;

 bottom:0;

 left:0;

 background-color:#f2f2f2;

 opacity:.95;

 width: 100%;

 }

","#_bd {z-index:8675311;

 position: absolute;

 text-align: left;

 padding-top: 38px;

 width: 100%;

 top: 0;

 left: 0;

 right: 0;

 font:16px hevetica neue,arial,san-serif;

 }

","#_bd i { font-style:normal;

 }

","#_bd a#_x { z-index:8675332;

 position: fixed;

 *position:absolute;

 width:100%;

 top: 0;

 left: 0;

 right: 0;

 cursor: pointer;

 height: 37px;

 line-height: 36px;

 font-size: 14px;

 font-weight: bold;

 display: block;

 margin: 0;

 background: url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/fullGradient07Normal.png) repeat-x scroll 0 0 #FFFFFF;

 border-bottom: 1px solid #aaa;

 color: #211922;

 text-align: center;

}

",
"#_bd a#_x:active {background-color: #211922;

 background-image: url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/fullGradient07Inverted.png);

 border-color: #211922;

 text-shadow: 0 -1px #211922;

 }

","#_bd a#_x:hover {color: #fff;

 text-decoration: none;

 background-color: #900;

 border-color: #900;

 text-shadow: 0 -1px #900;

}

","#_bd span { z-index:8675312;

 height:200px;

 width:200px;

 overflow:hidden;

 zoom:1;

 display:inline-block;

 background: #fff;

 text-shadow: 0 1px #fff;

 position: relative;

 vertical-align:middle;

 border: 1px solid #aaa;

 border-top: none;

 border-left: none;

}

",
"#_bd span#_logo {background: #FCF9F9 url('.theme_get_setting('logo').') 50% 50% no-repeat;

}

","#_bd span a {z-index:8675314;

 cursor: pointer;

 height: 200px;

 width: 200px;

 }

","#_bd span a img { z-index: 8675316;

 position: absolute;

 top: 0;

 left: 0;

 border: 0;

 margin: 0;

 }

","#_bd span a b {z-index: 8675317;

  position: absolute;

 top: 50%;

 left: 50%;

 height: 50px;

 width: 50px;

 background: transparent url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/VideoIndicator.png) 0 0 no-repeat;

 margin-top: -25px;

 margin-left: -25px;

 }

","#_bd span a cite {z-index: 8675317;

  position: absolute;

 font-size: 10px;

 font-style: normal;

 bottom: 5px;

 width: 100px;

 left: 50%;

 margin-left: -50px;

 text-align: center;

 color: #000;

 background: #fff;

 padding: 3px;

}

",
"#_bd span._pinContainer span._pinButton {z-index: 8675318;

  line-height: 200px;

 font-size: 200px;

 cursor: pointer;

 position: absolute;

 top: 0;

 left: 0;

 height:200px;

 width:200px;

 background: transparent;

 }

","#_bd span._pinContainer span._pinButton:hover {background: transparent url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/W.png) 50% 50% no-repeat;

 }

","#_bd span._pinContainer span._hideMe { z-index: 8675332;

position: absolute;

 height: 200px;

 width: 200px;

 background: rgba(128, 128, 128, .5);

 *background: #aaa;

 line-height: 200px;

 font-size: 10px;

 color: #fff;

 text-align: center;

 font-weight: normal!important;

 }

"]}

);

');
    } else {
        $url = str_replace(array('http:','https:'),'',url('bookmarks_clone', array('absolute' => TRUE)));
        print str_replace(array("\n","\r"),'','
(function(k,o,p,l){
	var a=k[l.k]={w:k,d:o,n:p,a:l,s:{
  }, f:function(){
		return{
			callback:[],kill:function(b){
				b.parentNode&&b.parentNode.removeChild(b)
			}, get:function(b,c){
				var e=null;
				return e=b[c]||b.getAttribute(c)
			}, make:function(b){
				var c=false,e,d;
				for(e in b)if(b[e].hasOwnProperty){
					c=a.d.createElement(e);
					for(d in b[e]) if(b[e][d].hasOwnProperty) if(typeof b[e][d]==="string") c[d]=b[e][d];
					break
				}

				return c
			} ,listen:function(b,c,e){
				if(typeof a.w.addEventListener!=="undefined")b.addEventListener(c,e,false);
				else typeof a.w.attachEvent!=="undefined"&&b.attachEvent("on"+c,e)
			}, getSelection:function(){
				return(""+(a.w.getSelection?a.w.getSelection():a.d.getSelection?a.d.getSelection():a.d.selection.createRange().text)).replace(/(^\s+|\s+$)/g,"")
			}, pin:function(b){
				var c=b.getElementsByTagName("IMG")[0],e="false",d=a.a.pin+"?",f=(new Date).getTime();
				if(b.rel==="video")e="true";
				d=d+"media="+encodeURIComponent(c.src);
				d=d+"&url="+encodeURIComponent(c.getAttribute("url")||a.d.URL);
				d=d+"&title="+encodeURIComponent(a.d.title);
				d=d+"&is_video="+e;
				d=d+"&description="+encodeURIComponent(a.v.selectedText||c.title||c.alt);
				a.v.hazIOS&&a.w.setTimeout(function(){
					a.w.location="pinit12:"+d
				}, 25);
				a.w.open(d,"pin"+f,a.a.pop)
			}, close:function(b){
				if(a.s.bg){
					a.d.b.removeChild(a.s.shim);
					a.d.b.removeChild(a.s.bg);
					a.d.b.removeChild(a.s.bd)
				}

				k.hazPinningNow=false;
				b&&a.w.alert(b);
				a.v.hazGoodUrl=false;
				a.w.scroll(0,a.v.saveScrollTop)
			}, click:function(b){
				b=b||a.w.event;
				var c=null;
				if(c=b.target?b.target.nodeType===3?b.target.parentNode:b.target:b.srcElement)
					if(c===a.s.x)
					  a.f.close();
					else
						if(c.parentNode.className===a.a.k+"_pinContainer"||c.className===a.a.k+"_pinButton"){
							a.f.pin(c.parentNode.getElementsByTagName("A")[0]);
							a.w.setTimeout(function(){
								a.f.close()
							},10)
						}
			}, behavior:function(){
				a.f.listen(a.s.bd,"click",a.f.click)
			}, presentation:function(){
				var b=a.f.make({
					STYLE:{
						type:"text/css"
					}
				}),c=a.a.rules.join("\n").replace(/#_/g,"#"+l.k+"_").replace(/\._/g,"."+l.k+"_");
				if(b.styleSheet)b.styleSheet.cssText=c;
				else b.appendChild(a.d.createTextNode(c));
				a.d.h.appendChild(b)
			}, thumb:function(b,c,e,d,f,g){
				if(a.v.hazSrc[b]!==true)a.v.hazSrc[b]=true;
				else if(!a.v.hazIE)return;
				a.v.hazAtLeastOneGoodThumb=true;
				d||(d="image");
				var h=a.f.make({
					SPAN:{
						className:a.a.k+"_pinContainer"
					}
				}), j=a.f.make({
					A:{
						rel:d
					}
				}), i=new Image,m,n;
				i.setAttribute("nopin","nopin");
				i.style.visibility="hidden";
				if(f)i.title=f;
				g&&i.setAttribute("url",g);
				i.onload=function(){
					m=this.width;
					n=this.height;
					this.style.marginTop=n<a.a.thumbCellSize?-n/2+"px":"-"+a.a.thumbCellSize/2+"px";
					this.style.marginLeft=m<a.a.thumbCellSize?-m/2+"px":"-"+a.a.thumbCellSize/2+"px";
					this.style.visibility=""
				};
				i.src=b;
				j.appendChild(i);
				if(d!=="image"){
					b=a.f.make({
						B:{
						}
					});
					j.appendChild(b)
				}

				c=a.f.make({
					CITE:{
						innerHTML:c+" x "+e
					}

				});
				j.appendChild(c);
				h.appendChild(j);
				h.appendChild(a.f.make({
					SPAN:{
						className:a.a.k+"_pinButton"
					}

				}));
				if(d!=="image")(d=a.s.bd.getElementsByTagName("SPAN")[1])?d.parentNode.insertBefore(h,d):a.s.bd.appendChild(h);
				else a.s.bd.appendChild(h)
			}, call:function(b,c){
				var e=a.a.k+".f.callback["+a.f.callback.length+"]",d=a.d.createElement("SCRIPT");
				a.f.callback.push(function(f){
					c(f);
					a.f.kill(e)
				});
				d.id=e;
				d.src=b+e;
				d.type="text/javascript";
				d.charset="utf-8";
				a.v.firstScript.parentNode.insertBefore(d,a.v.firstScript)
			}, ping:{
				check:function(b){
					b&&b.ok===false&&a.f.close(a.a.msg.noPin)
				}, vimeo:function(b){
					var c;
					if(b[0]&&b[0].thumbnail_large&&b[0].embed_privacy==="anywhere"){
						c="";
						if(b[0].title)c+=b[0].title;
						if(b[0].user_name)c=c+". Video by "+b[0].user_name;
						if(b[0].user_description)c=c+". "+b[0].user_description;
						c+=".";
						a.f.thumb(b[0].thumbnail_large,150,200,"video",c,b[0].url)
					}
				}
			}, hazUrl:{
				vimeo:function(){
				var b=a.d.URL.split("/").pop(),c=a.d.getElementsByTagName("LI"),e=a.d.getElementsByTagName("A"),d,f;
				b=parseInt(b,10);
				if(b>1&&a.v.hazCalledForThumb["_"+b]!==true){
					a.f.call("http://vimeo.com/api/v2/video/"+b+".json?callback=",a.f.ping.vimeo);
					a.v.hazCalledForThumb["_"+b]=true
				}

				d=c.length;
				for(f=0; f<d; f+=1) if(c[f].id&&c[f].id.split("clip_")[1]){
					b=c[f].id.split("clip_")[1];
					b=parseInt(b,10);
					if(b>1&&a.v.hazCalledForThumb["_"+b]!==true){
						a.v.hazCalledForThumb["_"+b]=true;
						a.f.call("http://vimeo.com/api/v2/video/"+b+".json?callback=",a.f.ping.vimeo)
					}
				}

				d=e.length;
				for(f=0; f<d; f+=1)if(e&&e[f].href){
					b=parseInt(e[f].href.split("/").pop(),10);
					if(b>1&&a.v.hazCalledForThumb["_"+b]!==true){
						a.f.call("http://vimeo.com/api/v2/video/"+b+".json?callback=",a.f.ping.vimeo);
						a.v.hazCalledForThumb["_"+b]=true
					}
				}
			}, pinterest:function(){
				a.f.close(a.a.msg.installed)
			}, facebook:function(){
				a.f.close(a.a.msg.privateDomain.replace(/%privateDomain%/,"Facebook"))
			}, googleReader:function(){
				a.f.close(a.a.msg.privateDomain.replace(/%privateDomain%/,"Google Reader"))
			}, stumbleUpon:function(){
				var b=0,c=a.a.stumbleFrame.length,e;
				for(b=0; b<c; b+=1)if(e=a.d.getElementById(a.a.stumbleFrame[b])){
					a.f.close();
					if(a.w.confirm(a.a.msg.bustFrame)){
						a.d.location=e.src;
						a.w.open(e.src)
					}

					break
				}
			}
		}, hazSite:{
			youtube:{
				iframe:function(b){
					b=b.src.split("?")[0].split("&")[0].split("/");
					a.f.thumb("http://img.youtube.com/vi/"+b.pop()+"/0.jpg",360,480,"video")
				}, video:function(b){
					b.getAttribute("data-youtube-id")&&a.f.thumb("http://img.youtube.com/vi/"+b.getAttribute("data-youtube-id")+"/0.jpg",360,480,"video")
				}, embed:function(b){
					var c=b.getAttribute("flashvars"),e="";
					(e=c?c.split("video_id=")[1].split("&")[0]:b.src.split("?")[0].split("&")[0].split("/").pop())&&a.f.thumb("http://img.youtube.com/vi/"+e+"/0.jpg",360,480,"video")
				}, object:function(b){
					b=b.getAttribute("data");
					var c="";
					if(b)c=b.split("?")[0].split("&")[0].split("/").pop();
					c&&a.f.thumb("http://img.youtube.com/vi/"+c+"/0.jpg",360,480,"video")
				}
			}, vimeo:{
				iframe:function(b){
					a.f.call("http://vimeo.com/api/v2/video/"+b.src.split("/").pop()+".json?callback=",a.f.ping.vimeo)
				}

			}

		},hazTag:{
			img:function(b){
				var c;
				if(!b.src.match(/^data/)){
					c=new Image;
					c.src=b.src;
					c.height>a.a.minImgSize&&c.width>a.a.minImgSize&&a.f.thumb(c.src,c.height,c.width)
				}
			},meta:function(b){
				b.name&&b.name.toUpperCase()==="PINTEREST"&&b.content&&b.content.toUpperCase()==="NOPIN"&&a.f.close(a.a.msg.noPin)
			}
		},checkTags:function(){
			var b,c,e,d,f,g,h,j,i;
			a.v.tag=[];
			b=0;
			for(c=a.a.check.length; b<c; b+=1){
				f=a.d.getElementsByTagName(a.a.check[b]);
				e=0;
				for(d=f.length; e<d; e+=1){
					g=f[e];
					!g.getAttribute("nopin")&&g.style.display!=="none"&&g.style.visibility!=="hidden"&&a.v.tag.push(g)
				}
			}

			b=0;
			for(c=a.v.tag.length;b<c;b+=1){
				f=a.v.tag[b];
				g=f.tagName.toLowerCase();
				if(a.f.hazTag[g])
					a.f.hazTag[g](f);
				else
					if(a.a.tag[g])for(h in a.a.tag[g])if(a.a.tag[g][h].hasOwnProperty){
				j=a.a.tag[g][h];
				if(i=a.f.get(f,j.att)){
					e=0;
					for(d=j.match.length; e<d;e+=1)i.match(j.match[e])&&a.f.hazSite[h][g](f)
				}
			}
		}
	},structure:function(){
		a.s.shim=a.f.make({
			IFRAME:{
				height:"100%",width:"100%",allowTransparency:true,id:a.a.k+"_shim"
			}
		});
		a.s.shim.setAttribute("nopin","nopin");
		a.d.b.appendChild(a.s.shim);
		a.s.bg=a.f.make({
			DIV:{
				id:a.a.k+"_bg"
			}
		});
		a.d.b.appendChild(a.s.bg);
		a.s.bd=a.f.make({
			DIV:{
				id:a.a.k+"_bd"
			}
		});
		a.s.x=a.f.make({
			A:{
				id:a.a.k+"_x",innerHTML:a.a.msg.cancelTitle
			}
		});
		a.s.bd.appendChild(a.s.x);
		a.s.bd.appendChild(a.f.make({
			SPAN:{
				id:a.a.k+"_logo"
			}
		}));
		a.d.b.appendChild(a.s.bd);
		a.w.scroll(0,0)
	},checkUrl:function(){
		var b;
		for(b in a.a.url)if(a.a.url[b].hasOwnProperty)if(a.d.URL.match(a.a.url[b])){
			a.f.hazUrl[b]();
			if(a.v.hazGoodUrl===false)return false
		}

		return true
	},checkPage:function(){
		if(a.f.checkUrl()){
			a.f.checkTags();
			if(a.v.hazGoodUrl===false)return false
		}
		else return false;
		return true
	},init:function(){
		a.d.b=a.d.getElementsByTagName("BODY")[0];
		a.d.h=a.d.getElementsByTagName("HEAD")[0];
		if(!(!a.d.b||!a.d.h||k.hazPinningNow===true)){
			var b,c=a.n.userAgent;
			a.v={
				saveScrollTop:a.w.pageYOffset,hazGoodUrl:true,hazAtLeastOneGoodThumb:false,hazSrc:{
			},hazCalledForThumb:{
		},hazIE:function(){
			return/msie/i.test(c)&&!/opera/i.test(c)
		}(),hazIOS:function(){
			return c.match(/iP/)!==null
		}(),firstScript:a.d.getElementsByTagName("SCRIPT")[0],selectedText:a.f.getSelection()
	};
	b=a.a.checkpoint.url+"?url="+encodeURIComponent(a.d.URL)+"&callback=";
	a.f.call(b,a.f.ping.check);
	a.f.structure();
	a.f.presentation();
	if(a.f.checkPage())if(a.v.hazGoodUrl===true){
		a.f.behavior();
		if(!(a.f.callback.length>1))if(a.v.hazAtLeastOneGoodThumb===false||a.v.tag.length===0){
			a.f.close(a.a.msg.notFound);
			return
		}
	}

	k.hazPinningNow=true
}
}
}
}()
};
a.f.init()
})(window,document,navigator,{
	k:"PIN_"+(new Date).getTime(),
	checkpoint:{
		url:"'.$url.'"
	},pin:"'.$url.'",minImgSize:80,thumbCellSize:200,check:["meta","iframe","embed","object","img","video"],
		url:{
			vimeo:/^https?:\/\/.*?\.?vimeo\.com\//,facebook:/^https?:\/\/.*?\.?facebook\.com\//,googleReader:/^https?:\/\/.*?\.?google\.com\/reader\//,pinterest:/^https?:\/\/.*?\.?pinterest\.com\//,stumbleUpon:/^https?:\/\/.*?\.?stumbleupon\.com\//
		},
		stumbleFrame:["tb-stumble-frame","stumbleFrame"],
		tag:{
		video:{
			youtube:{
				att:"src",
				match:[/videoplayback/]
			}
		},
		embed:{
			youtube:{
				att:"src",match:[/^http:\/\/s\.ytimg\.com\/yt/,/^http:\/\/.*?\.?youtube-nocookie\.com\/v/]
			}
		},
		iframe:{
			youtube:{
				att:"src",match:[/^http:\/\/www\.youtube\.com\/embed\/([a-zA-Z0-9\-_]+)/]
			},
			vimeo:{
				att:"src",match:[/^http?s:\/\/vimeo.com\/(\d+)/,/^http:\/\/player\.vimeo\.com\/video\/(\d+)/]
			}
		},
		object:{
			youtube:{
				att:"data",match:[/^http:\/\/.*?\.?youtube-nocookie\.com\/v/]
			}
		}
	},
	msg:{
		check:"",
		cancelTitle:"'.$t0.'",
		bustFrame:"'.$t1.'",
		noPin:"'.$t2.'",
		privateDomain:"'.$t3.'",
		notFound:"'.$t4.'",
		installed:"'.$t5.'"
	},
	pop:"status=yes,resizable=yes,scrollbars=yes,personalbar=no,directories=yes,location=yes,toolbar=yes,menubar=yes,left=0,top=0",
		rules:["#_bg {
		position:fixed;
		z-index:8675309;
 		top:0;
 		right:0;
 		bottom:0;
 		left:0;
 		background-color:#e2e2e2;
 		opacity:.95;
	}","
	#_shim {
		position:fixed;
 		background: transparent;
 		z-index:8675308;
 		top:0;
 		right:0;
 		bottom:0;
 		left:0;
	}","
	#_bd {
		position: absolute;
 		text-align: left;
 		padding-top: 36px;
 		top: 0;
 		left: 0;
 		right: 0;
 		z-index:8675320;
 		font:16px hevetica neue,arial,san-serif;
	}","
	#_bd span {
 		zoom:1;
 		display: inline-block;
 		background: #fff;
 		height:200px;
 		width:200px;
 		border: 1px solid #bbb;
 		border-top: none;
 		border-left:none;
 		text-decoration: none;
  	text-shadow: 0 1px #fff;
 		position: relative;
 		cursor: pointer;
 		vertical-align:middle;
	}","
	#_bd span#_logo {
		background: #FCF9F9 url('.theme_get_setting('logo').') 50% 50% no-repeat;
 		box-shadow: none;
	}","
	#_bd a#_x {
		height: 36px;
 		line-height: 36px;
 		position: fixed;
 		font-size: 14px;
 		font-weight: bold;
 		display: block;
 		width:auto;
 		top: 0;
 		left: 0;
 		right: 0;
 		margin: 0;
 		background: url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/fullGradient07Normal.png) repeat-x scroll 0 0 #FFFFFF;
 		border-bottom: 1px solid #bbb;
 		color: #211922;
 		text-align: center;
 		z-index:8675321;
	}","
	#_bd a#_x:active {
		background-color: #211922;
 		background-image: url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/fullGradient07Inverted.png);
 		border-color: #211922;
 		text-shadow: 0 -1px #211922;
	}","
	#_bd a#_x:hover {
		color: #fff;
 		text-decoration: none;
 		background-color: #900;

 		border-color: #900;
 		text-shadow: 1px 1px #600;
	}","
	#_bd a img {
		max-height:200px;
 		max-width:200px;
 		top: 50%;
 		left: 50%;
 		position: absolute;
 		z-index:8675312;
	}","
	#_bd a b {
 		z-index: 8675315;
 		position: absolute;
 		top: 50%;
 		left: 50%;
 		height: 50px;
 		width: 50px;
 		background: transparent url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/VideoIndicator.png) 0 0 no-repeat;
 		margin-top: -25px;
 		margin-left: -25px;
	}","
	#_bd a cite {
		z-index: 8675316;
 		position: absolute;
 		font-size: 10px;
 		font-style: normal;
 		bottom: 5px;
 		width: 100px;
 		left: 50%;
 		margin-left: -50px;
 		text-align: center;
 		color: #000;
 		background: #fff;
 		padding: 3px;
	}","
	#_bd span._pinContainer {
		z-index: 8675320;
 		height: 200px;
 		width: 200px;
 		background: #fff;
	}","
	#_bd span._pinButton {
		z-index: 8675320;
 		height: 200px;
 		width: 200px;
 		background: transparent;
	}","
	#_bd span._pinButton:hover {
		height: 200px;
 		width: 200px;
 		background: transparent url('.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/W.png) 50% 50% no-repeat;
	}"]

});
');
    }
    exit;
}

function cats_bookmarking_addboardpin () {
    global $base_url;
    $out = '';
    $out .= '<div class="PinButtonB">'.l('<img src="'.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/pinitbutton.png" /><br />'.t('"Wish It" Button'), 'addpinitb', array('html' => TRUE));
    $out .= l('<img src="'.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/createpin.png" /><br />'.t('Upload a Pin'), 'node/add/pin', array('html' => TRUE));
    $out .= l('<img src="'.$base_url.'/'.drupal_get_path('theme','maojie_china').'/images/board.png" /><br />'.t('Create a Board'), 'board/add', array('html' => TRUE)).'</div>';
    return t($out);
}

function cats_bookmarking_addpinit () {
    if (isset($GLOBALS['conf']['clean_url'])) $t = '?'; else $t = '&';
    $url = url('pinit1', array('absolute' => TRUE)).$t;
    $out = '';
 //$out .= '<div id="PinItButtonContainer"><div id="PinButton"><div id="ButtonHolder"><a onclick="alert(\''.t('Drag me to the bookmarks bar').'\'); return false;" href="javascript:void((function(){var e=document.createElement(\'script\');e.setAttribute(\'type\',\'text/javascript\');e.setAttribute(\'charset\',\'UTF-8\');e.setAttribute(\'src\',\''.$url.'r=\'+Math.random()*99999999);document.body.appendChild(e)})());" title="Wish It" id="BigPinItButton"><strong>'.'<imag src="http://dev.9catsave.com/sites/all/themes/maojie_china/images/W.png"/>'.t('Wish It').'</strong><span></span></a>';
    $out .= '</div><div id="PinItButtonContainer">
    <div id="PinButton">
        <div id="ButtonHolder">
        	<div class="overlay">
                <div class="drag-wrap">
					<div class="wishit-wrap">
						<div class="wishit-container">
							<h1>Add an image from any website to your collection!</h1>
							<p>(Drag this icon to your bookmark bar.)</p>
							<p>(*shortcut to display bookmark bar:ctrl+Shift+B)</p>
						 </div>
						 <a onclick="alert(\''.t('Drag me to the bookmarks bar').'\'); return false;" href="javascript:void((function(){var e=document.createElement(\'script\');e.setAttribute(\'type\',\'text/javascript\');e.setAttribute(\'charset\',\'UTF-8\');e.setAttribute(\'src\',\''.$url.'r=\'+Math.random()*99999999);document.body.appendChild(e)})());" title="Wish It" id="BigPinItButton">
							 <div class="wishit-icon">
							   <img src="sites/all/themes/xingyuyuan/images/drag-en.png" class="dragline">
							   <span class="wishit">'.t('Wish It').'</span>
							 </div>
						 </a>
						<div class="wishit-btns">
							<div class="back-btn"><a href="javascript:" class="back_bta">Back</a></div>
							<div class="back-btn"><a href="http://www.wishary.in/">Home</a></div>
						</div>
					</div>
                    
                </div>
            </div>
        </div>
    </div>
</div>';
    //$out .= '<p id="ButtonInstructions"> &nbsp;&nbsp;'.t('Add this link to your Bookmarks Bar').'</p></div>';
 
    /*$out .= '<p>'.t('To install the "Wish It" button in your Browser:').'</p>';
    $out .= '<div id="InstallationInstructions" class="small"><ol>';
    $out .= '<li>'.t('Display your Bookmarks Bar by clicking View &gt; Toolbars &gt; Bookmarks Toolbar').'</li>';
    $out .= '<li>'.t('Drag the "Wish It" button to your Bookmarks Toolbar').'</li>';
    $out .= '<li>'.t('When you are browsing the web, push the "Wish It" button to make a wish by extracting image').'</li>';
    $out .= '</ol></div>';
    $out .= '<p>'.t('Once installed in your browser, the "Wish It" button lets you grab an image from any website and add it to one of your collections. When you wish from a website, we automatically grab the source link so we can credit the original creator.').'</p>';
    $out .= '</div></div>';*/
    return $out;
}
function cats_bookmarking_recomment () {
    if (isset($GLOBALS['conf']['clean_url'])) $t = '?'; else $t = '&';
    $url = url('recommend1', array('absolute' => TRUE)).$t;
    $out = '';
 //$out .= '<div id="PinItButtonContainer"><div id="PinButton"><div id="ButtonHolder"><a onclick="alert(\''.t('Drag me to the bookmarks bar').'\'); return false;" href="javascript:void((function(){var e=document.createElement(\'script\');e.setAttribute(\'type\',\'text/javascript\');e.setAttribute(\'charset\',\'UTF-8\');e.setAttribute(\'src\',\''.$url.'r=\'+Math.random()*99999999);document.body.appendChild(e)})());" title="Wish It" id="BigPinItButton"><strong>'.'<imag src="http://dev.9catsave.com/sites/all/themes/maojie_china/images/W.png"/>'.t('Wish It').'</strong><span></span></a>';
    $out .= '</div><div id="PinItButtonContainer">
    <div id="PinButton">
        <div id="ButtonHolder">
        	<div class="overlay">
                <div class="drag-wrap">
					<div class="wishit-wrap">
						<div class="wishit-container">
							<h1>Recommend a product from any website to the posts added in your bucket list!</h1>
							<p>(Drag this icon to your bookmark bar.)</p>
							<p>(*shortcut to display bookmark bar:ctrl+Shift+B)</p>
						 </div>
						 <a onclick="alert(\''.t('Drag me to the bookmarks bar').'\'); return false;" href="javascript:void((function(){var e=document.createElement(\'script\');e.setAttribute(\'type\',\'text/javascript\');e.setAttribute(\'charset\',\'UTF-8\');e.setAttribute(\'src\',\''.$url.'r=\'+Math.random()*99999999);document.body.appendChild(e)})());" title="Recommend It" id="BigPinItButton">
							 <div class="wishit-icon">
							   <img src="sites/all/themes/xingyuyuan/images/drag-en.png" class="dragline">
							   <span class="wishit">'.t('Recommend It').'</span>
							 </div>
						 </a>
						<div class="wishit-btns">
							<div class="back-btn"><a href="javascript:" class="back_bta">Back</a></div>
							<div class="back-btn"><a href="http://www.wishary.in/">Home</a></div>
						</div>
					</div>
                    
                </div>
            </div>
        </div>
    </div>
</div>';
    //$out .= '<p id="ButtonInstructions"> &nbsp;&nbsp;'.t('Add this link to your Bookmarks Bar').'</p></div>';
 
    /*$out .= '<p>'.t('To install the "Wish It" button in your Browser:').'</p>';
    $out .= '<div id="InstallationInstructions" class="small"><ol>';
    $out .= '<li>'.t('Display your Bookmarks Bar by clicking View &gt; Toolbars &gt; Bookmarks Toolbar').'</li>';
    $out .= '<li>'.t('Drag the "Wish It" button to your Bookmarks Toolbar').'</li>';
    $out .= '<li>'.t('When you are browsing the web, push the "Wish It" button to make a wish by extracting image').'</li>';
    $out .= '</ol></div>';
    $out .= '<p>'.t('Once installed in your browser, the "Wish It" button lets you grab an image from any website and add it to one of your collections. When you wish from a website, we automatically grab the source link so we can credit the original creator.').'</p>';
    $out .= '</div></div>';*/
    return $out;
}
