<?php
/**
 * @file
 * Node Lazyloader Install
 *
 * @author: Daniel Honrade http://drupal.org/user/351112
 *
 */


/**
 * Implements hook_install().
 */
function nodelazyloader_install() {
  // Make sure this module called last
  // to override any form provided by other modules
  db_query("UPDATE {system} SET weight = 2080 WHERE name = 'nodelazyloader'");
}


/**
 * Implements hook_uninstall().
 */
function nodelazyloader_uninstall() {
  variable_del('nodelazyloader');
}
