<?php
/*
 * Implementation of hook_image_default_styles().
 */
include_once(drupal_get_path('module', 'tb_wall_layout') . '/tb_wall_layout.inc');

function tb_wall_layout_image_default_styles() {
  $styles = array();

  $styles['tb-wall-dynamic-style'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 750, 'height' => '', 'upscale' => 1),
        'weight' => '0',
      ),
    ),
  );

  $styles['tb-wall-single-style'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 250, 'height' => '', 'upscale' => 1),
        'weight' => '0',
      ),
    ),
  );

  $styles['tb-wall-double-style'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 500, 'height' => '', 'upscale' => 1),
        'weight' => '0',
      ),
    ),
  );
  $styles['tb-wall-triple-style'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 750, 'height' => '', 'upscale' => 1),
        'weight' => '0',
      ),
    ),
  );
  return $styles;
}

