<?php

/**
 * Implementation of hook_menu()
 */
function guest_menu() {
  $items['remix_banner'] = array(
    'title' => 'guest',
    'type' => MENU_CALLBACK,
    'page callback' => 'guest_callback_banner',
     'access callback' => TRUE,
  );
   $items['remix_blog'] = array(
    'title' => 'guest',
    'type' => MENU_CALLBACK,
    'page callback' => 'guest_callback_blog',
     'access callback' => TRUE,
  );
   $items['remix_style'] = array(
    'title' => 'guest',
    'type' => MENU_CALLBACK,
    'page callback' => 'guest_callback_style',
     'access callback' => TRUE,
  );


  return $items;
}


$offset=$_REQUEST['offset'];
$limit=$_REQUEST['limit'];
//$for_you =array_unique($for_you);
$for_you=array_slice($for_you,$offset,$limit);

    drupal_json_output($for_you);
    exit();
//return json_encode($for_you);
}